### ISSUE TITLE
[1.12.2] Filing Cabinet does not rotate / face player when placed

### ISSUE THREAD

**Issue by Luke616** [AshIndigo/Filing_Cabinet#1]
Title, the filing cabinet will only face in one predefined direction, rather than rotating to facing forwards towards the player when placed like chests/logs/etc do

Storage Cabinet v1.0
Minecraft 1.12.2
Forge 2768

**Comment by AshIndigo** [comment]
Updated version with the fix has been uploaded to curse, should get approved soon. Thanks for telling me and sorry about the delay.

**Comment by Luke616** [comment]
No problem, thanks for the fix!
