### ISSUE TITLE
please try to improve the IsValid() Method of the Cabinet Manager

### ISSUE THREAD

**Issue by MSandro** [AshIndigo/Filing_Cabinet#11]
![image](https://user-images.githubusercontent.com/10937159/132653698-4a783091-dc3d-4f3b-afe8-cbcae034109a.png)
Yesterday I've tried to find out what is lagging my server so much. My 2 Cabinet Managers are often causing very long tick durations. There are just 2 Managers in my world, one hast 8 cabinets and the other 16.

**Comment by AshIndigo** [comment]
I'll look into it as soon as can

Sadly had to bring in my main computer, the one I mod in for repairs

Gonna see if I cant get a dev environment set up on a spare machine tommorow to be able to look at this issue though, hopefully it's powerful enough to handle modding

**Comment by AshIndigo** [comment]
Gonna close for now since the performance has been improved. Gonna probably upload the new build to CF tonight or something
