### ISSUE TITLE
Storage Cabinet does not rotate / face player in multiplayer

### ISSUE THREAD

**Issue by Luke616** [AshIndigo/Filing_Cabinet#2]
Hey, thanks again for fixing my previous issue. Everything is working great in singleplayer but unfortunately in multiplayer the issue seems to still be there - regardless of orientation when placing the cabinet, it will always face north.

Storage Cabinet v1.0.1
Minecraft 1.12.2
Forge 2808

Related Issue: https://github.com/AshIndigo/Filing_Cabinet/issues/1

Thanks,
Luke616

**Comment by AshIndigo** [comment]
Just uploaded v1.0.2 onto curse, that should fix the issue for you.
Thanks for reporting this!
