### ISSUE TITLE
funnel compatibility

### ISSUE THREAD

**Issue by Dr-WeiAL** [AshIndigo/Filing_Cabinet#25]
https://github.com/Fabricators-of-Create/Create/issues/166
Well, they say it needs to be fixed here

**Comment by AshIndigo** [comment]
Well it's a year late. But I got funnel's working on 1.19.2 at least in my dev environment
A new version will be on CF after I do a few more checks and make sure I didn't break anything

**Comment by Dr-WeiAL** [comment]
Well, it's surprising that this issue was noticed
Does that mean it will only be fixed in 1.19.2? I feel like more people want to fix 1.18.2 as well

**Comment by AshIndigo** [comment]
I burn out easily TBH, getting back into the groove of modding for a bit.
Can't be too hard to backport though, I'll look into it.
