### ISSUE TITLE
Rotating a filing cabinet purges content

### ISSUE THREAD

**Issue by Simon-Bitdiddle** [AshIndigo/Filing_Cabinet#5]
If you hit a filing cabinet with any content with a wrench to rotate it, the content disappears.

**Comment by AshIndigo** [comment]
Which version? MC and mod ver preferably

**Comment by Simon-Bitdiddle** [comment]
MC 1.12.2
StorageCabinet 1.1.0

This is from the Dungeons, Dragons, and Space Ships modpack

**Comment by AshIndigo** [comment]
Fixed, new build will be on CurseForge I'll close this issue once it's approved. Thanks for telling me

**Comment by AshIndigo** [comment]
Approved, https://www.curseforge.com/minecraft/mc-mods/storage-cabinet/files/2797187
